In [1]:
%reload_ext dotenv

In [2]:
from pathlib import Path
from dotenv import load_dotenv
env_file = Path("/Users/lvalverdeb/TeamDev/repo-split/boti/.env.local")
load_dotenv(dotenv_path=env_file)

True

In [3]:
import os
db_url_async = os.getenv('ASYNC_DB_DSN')
db_url_sync = os.getenv('SYNC_DB_DSN')

In [4]:
db_url_async

'mysql+asyncmy://ibis:kLdovG7BXPRloPk@ic-db02.istmocenter.com:3306/istmo360n'

In [5]:
from pydantic import SecretStr
from boti_data import SqlDatabaseConfig, AsyncSqlDatabaseResource, SqlDatabaseResource

config_sync=SqlDatabaseConfig(connection_url=SecretStr(db_url_sync))
config_async=SqlDatabaseConfig(connection_url=SecretStr(db_url_async))

In [6]:
with SqlDatabaseResource(config_sync) as db:
    print(f"Connected smoothly against underlying engine: {str(db.engine)}")
    from boti_data.db.sql_model_registry import get_global_registry

    registry = get_global_registry()

    RolesModel = registry.get_model(engine=db.engine, table_name="panel_roles")

    print(f"Dynamic Model Mapping Evaluated: {RolesModel}")
    print(f"Target Table Binding: {RolesModel.__tablename__}")
    print(f"Reflected Features: {[c.name for c in RolesModel.__table__.columns]}")

Connected smoothly against underlying engine: Engine(mysql+pymysql://ibis:***@ic-db02.istmocenter.com:3306/istmo360n)
Dynamic Model Mapping Evaluated: <class 'boti_data.dynamic_models.PanelRoles'>
Target Table Binding: panel_roles
Reflected Features: ['role_id', 'role_description', 'sys_admin', 'panel_user', 'role_scope']

In [7]:
from boti_data.helper import DataHelper
config={
    'backend': 'sqlalchemy',
    'connection_url': db_url_sync,
    "poolclass": "sqlalchemy.pool.NullPool",
    "worker_connection_env_var": "SYNC_DB_DSN",
    'query_only': True,
    'table': 'asm_tracking_productos',
    'field_map': {
        'id_track_global': 'global_track_id',
        'id_tipo_producto': 'product_type_id'
    },
    'sticky_filters': {
        'product_type_id': 1,
    },
}

In [8]:
gateway = DataHelper(**config)

In [9]:
result = await gateway.aload(global_track_id__in=[1,2,3,4])

In [10]:
result.compute()

,id_producto,product_type_id,id_sitio,cliente_id,id_corte,codigo_barra,numero_cedula,nombre_th,apellido1_th,apellido2_th,...,id_provincia_recoleccion,id_canton_recoleccion,id_distrito_recoleccion,id_pais_recoleccion,sub_estatus,escaneado,extra_data,sucursal,placa_vehiculo_formalizador,uuid
0,405720434,1,1000000,139,178167,IST011198366CR,504220724,MARCOS V ARGUEDAS L,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,1,1,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,254d6a3b-740f-11f1-b32b-bc24112125eb
1,405728377,1,1000000,139,178315,16332250,16332250,Jose,Delgado,Perez,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,25603c37-740f-11f1-b32b-bc24112125eb
2,405787038,1,1000000,139,180171,117680671,117680671,JOSHUA,MICHAEL,ARIAS,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,260457ea-740f-11f1-b32b-bc24112125eb
3,405787039,1,1000000,139,180172,117680672,117680672,JOSHUA,ALFREDO,CAMPOS,...,<NA>,<NA>,<NA>,<NA>,1,1,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,26045849-740f-11f1-b32b-bc24112125eb
4,405787040,1,1000000,139,180173,117680673,117680673,JOSHUA,ALFARO,CAMPOS,...,<NA>,<NA>,<NA>,<NA>,1,1,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,260458a0-740f-11f1-b32b-bc24112125eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15124,408518436,1,1000000,304,309671,BCT00000022,502950010,RICARDO,CERDAS,FONSECA,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,22aa13ea-7a1e-11f1-b32b-bc24112125eb
15125,408518437,1,1000000,304,309671,BCT00000032,113420028,SILVIA,LEON,SERRANO,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,12029190-87dd-11ef-9dd7-02420c001d02,<NA>,22aa4624-7a1e-11f1-b32b-bc24112125eb
15126,408518438,1,1000000,304,309671,BCT00000018,110020556,SOFIA,RODRIGUEZ,VALENZUELA,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,22aa9e5a-7a1e-11f1-b32b-bc24112125eb
15127,408518439,1,1000000,304,309671,BCT00000039,401740106,WILFREDO,HERNANDEZ,MURILLO,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,12029190-87dd-11ef-9dd7-02420c001d02,<NA>,22aae735-7a1e-11f1-b32b-bc24112125eb
15128,408518440,1,1000000,304,309671,BCT00000024,108820818,YANCI,CAMBRONERO,SALAZAR,...,<NA>,<NA>,<NA>,<NA>,<NA>,0,<NA>,4b4fd6ca-85a2-11ef-b950-02420c001d02,<NA>,22aaf96b-7a1e-11f1-b32b-bc24112125eb

In [11]:
import pyarrow.fs as pafs
arrow_fs=None
client_kwargs = {
    "endpoint_url": os.environ.get("ETL_FS_ENDPOINT"),
}
arrow_kwargs = {
    "access_key": os.environ.get("ETL_FS_KEY"),
    "secret_key": os.environ.get("ETL_FS_SECRET"),
    "session_token": os.environ.get("ETL_FS_TOKEN"),
    "region": "us-east-1",
}
endpoint = client_kwargs.get("endpoint_url")
if endpoint:
    arrow_kwargs["endpoint_override"] = endpoint
    # PyArrow S3 usually infers scheme, but explicit is safer for custom endpoints
    arrow_kwargs["scheme"] = "https" if "https" in endpoint else "http"

try:
    arrow_fs = pafs.S3FileSystem(**arrow_kwargs)
except Exception as e:
    print(
        f"Could not create Native S3FileSystem: {e}. Falling back to wrapper."
    )

In [12]:
arrow_fs

In [13]:
from boti_data import ParquetReader

In [14]:
parquet_config = {
    'fs': arrow_fs,
    'storage_path': 'dst-etl/bronze/logistics/mobile/gps/',
    'parquet_start_date': '2026-01-01',
    'parquet_end_date': '2026-03-31',
    'partition_on': ['partition_date']
}
parquet_helper = ParquetReader(**parquet_config)

In [15]:
result = await parquet_helper.aload(associate_id__in=[27,4499])

In [16]:
result.compute()

,id,product_id,date_time,associate_id,latitude,longitude,direccion,action,description,server_dt,proveedor_gps,imei,android_id,partition_date
0,717299190,-1,2026-01-01 00:19:14+00:00,4499,9.852903,-83.902513,NaN,Reporte Posición,Monitoreo Regular,2026-01-01 00:19:19+00:00,fused,868149071422709,bde2d8709bfc335c,2026-01-01
1,717299191,-1,2026-01-01 00:19:14+00:00,4499,9.852903,-83.902513,NaN,Reporte Posición,Monitoreo Regular,2026-01-01 00:19:20+00:00,fused,868149071422709,bde2d8709bfc335c,2026-01-01
2,717299195,-1,2026-01-01 00:49:15+00:00,4499,9.852857,-83.902525,NaN,Reporte Posición,Monitoreo Regular,2026-01-01 00:49:18+00:00,fused,868149071422709,bde2d8709bfc335c,2026-01-01
3,717300183,-1,2026-01-01 00:53:18+00:00,4499,9.852856,-83.902519,NaN,Reporte Posición,Monitoreo Regular,2026-01-02 07:59:49+00:00,fused,868149071422709,bde2d8709bfc335c,2026-01-01
4,717300456,-1,2026-01-02 08:20:02+00:00,4499,9.939735,-84.051619,NaN,Reporte Posición,Monitoreo Regular,2026-01-02 08:24:12+00:00,fused,868149071422709,bde2d8709bfc335c,2026-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,718847123,-1,2026-03-31 14:30:57+00:00,4499,9.840749,-83.867171,NaN,Reporte Posición,Monitoreo Regular,2026-03-31 14:41:01+00:00,fused,868149071422709,bde2d8709bfc335c,2026-03-31
1420,718847910,-1,2026-03-31 14:51:58+00:00,4499,9.855553,-83.904453,NaN,Reporte Posición,Monitoreo Regular,2026-03-31 15:06:58+00:00,fused,868149071422709,bde2d8709bfc335c,2026-03-31
1421,718847911,-1,2026-03-31 15:03:53+00:00,4499,9.852892,-83.902515,NaN,Reporte Posición,Monitoreo Regular,2026-03-31 15:06:58+00:00,fused,868149071422709,bde2d8709bfc335c,2026-03-31
1422,718850227,-1,2026-03-31 15:14:04+00:00,4499,9.852882,-83.902459,NaN,Acceso o Salida,Acceso,2026-03-31 16:55:07+00:00,fused,868149071422709,903bfeb5d1b11444,2026-03-31
1423,718850261,-1,2026-03-31 15:13:37+00:00,4499,9.852870,-83.902494,NaN,Reporte Posición,Monitoreo Regular,2026-03-31 16:56:56+00:00,fused,868149071422709,bde2d8709bfc335c,2026-03-31

In [17]:
parquet_helper.close()